steps:

# - id: "Rodando go version"
#   name: 'gcr.io/cloud-builders/go'
#   env: ['PROJECT_ROOT=github.com/aguinelo/codeedu_desafiokubernetes']
#   args: ['version']
  
- id: "Rodando app test"
  name: 'gcr.io/cloud-builders/go'
  env: ['PROJECT_ROOT=github.com/aguinelo/codeedu_desafiokubernetes']
  args: ['test', './desafiogo/src/app']

- id: "Image Build"
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/aguinelo_desafikubernetes_app:latest', './desafiogo']

images:
  - 'gcr.io/$PROJECT_ID/aguinelo_desafikubernetes_app:latest'