steps:

- id: "Rodando app test"
  name: 'gcr.io/cloud-builders/go'
  # env: ['PROJECT_ROOT=/desafiogo/src/app']
  env:
    - GO111MODULE=on
  # dir: './desafiogo/src/app/'
  args: ['test', '.']

# - id: "Image Build"
#   name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'gcr.io/$PROJECT_ID/aguinelo_desafikubernetes_app:latest', './desafiogo']

# images:
#   - 'gcr.io/$PROJECT_ID/aguinelo_desafikubernetes_app:latest'