steps:

- id: "Rodando app test"
  name: 'gcr.io/cloud-builders/go'
  # env:
  #   - GO111MODULE=on
  #   - PROJECT_ROOT=./desafiogo/src/app
  # dir: './desafiogo/src/app/'
  # args: ['test', './desafiogo/src/app']
  args: ['version']

# - id: "Image Build"
#   name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'gcr.io/$PROJECT_ID/aguinelo_desafikubernetes_app:latest', './desafiogo']

# images:
#   - 'gcr.io/$PROJECT_ID/aguinelo_desafikubernetes_app:latest'