steps:

- id: "Rodando app test"
  name: 'gcr.io/cloud-builders/go'
  args: ['test', './desafiogo/src/app']

# - id: "Image Build"
#   name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'gcr.io/$PROJECT_ID/aguinelo_desafikubernetes_app:latest', './desafiogo']

# images:
#   - 'gcr.io/$PROJECT_ID/aguinelo_desafikubernetes_app:latest'