apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp
spec:
  selector:
    matchLabels:
      app: goapp
  replicas: 1
  template:
      metadata:
          labels:
            app: goapp
      spec:
        containers:
        - name: goapp
          image: aguinelo/aguinelo_desafikubernetes_app
          ports:
          - containerPort: 8000

          resources:
            requests:
              cpu: "200m"
              memory: "300Mi"

            limits:
              cpu: "250m"
